### ISSUE TITLE
Update section "Common CocoaPod Installation issues"

### ISSUE THREAD

**Issue by flexaddicted** [urbanairship/urbanairship-cordova#345] opened 2020-04-09 08:27 UTC
# Preliminary Info

### What Airship dependencies are you using?
urbanairship-cordova 10.1.1

### What are the versions of any relevant development tools you are using?

Xcode 11.4
cordova 9.0.0 (cordova-lib@9.0.1)

# Report

### What unexpected behavior are you seeing?
Installing urbanairship-cordova completes with the following error:

```
Installing "urbanairship-cordova" for ios
Failed to install 'urbanairship-cordova':Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/Users/xxxxx/xxxxx/test/platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
Error: pod: Command failed with exit code 1
```
### What is the expected behavior?
Installing urbanairship-cordova completes without errors.

### What are the steps to reproduce the unexpected behavior?
The steps to reproduce this error are described in the following bug.

https://github.com/apache/cordova-ios/issues/580

The issue, in fact, is related to the fact `cordova prepare` resets the ios platform in the Podfile to `10.0`.

**Comment by rlepinski** [comment] 2020-04-09 22:26
Thanks for the link, this has come up a few times since our last release that requires 11.

**Comment by marc-scig** [comment] 2020-04-13 21:10
@flexaddicted are you using cordova prepare, or just cordova-add? Also what version of cordova-ios is your app tied to?

**Comment by marc-scig** [comment] 2020-04-13 22:00
I can trigger the minimum deployment target regression mentioned in https://github.com/apache/cordova-ios/issues/580 if I remove the plugins/ and platforms/ directories, and then run cordova prepare. Otherwise it seems to be working fine. Just to be clear, does the issue adding the plugin go away if you manually update the deployment target in the Podfile?

If so I'm not really sure what we can do here, aside from adding a note on this to our docs, and hoping that the cordova ios team addresses the bug sometime soon.

**Comment by marc-scig** [comment] 2020-04-14 00:41
I can also reproduce by creating a new app without having specified a minimum target of iOS 11 in the config.xml. Running `cordova platform add ios` in this case will create a platforms/ios/Podfile with iOS 10, and it will persist that way unless you remove and re-add the iOS platform. If it gets in that state, the fix looks like:

- Update the config.xml file with the right minimum deployment target, if needed
- `cordova plugin remove urbanairship-cordova`
- `cordova platform remove ios`
- `cordova platform add ios`
- `cordova plugin add urbanairship-cordova`

On the other hand if the minimum target is already defined in config.xml and `platform/ios/Podfile` is just getting rewritten due to the `cordova prepare` bug, then it looks like you can just edit the Podfile directly. But the above should work as well.

**Comment by marc-scig** [comment] 2020-04-14 00:42
@flexaddicted I'll get the ball rolling to update our docs to make this more clear, but let me know if this helps.

**Comment by marc-scig** [comment] 2020-04-17 18:40
Closing this for now. Feel free to reopen it if you have any additional problems.

**Closed by marc-scig** 2020-04-17 18:40 UTC

**Comment by flexaddicted** [comment] 2020-04-19 15:32
@marc-scig sorry for the delay and thanks for your detailed answer.

Yeah, I've created an hook in order to restore the correct platform (iOS 11) when `cordova prepare` runs. Hope they will fix this soon.
